apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-3
  namespace: eks-sample-app
  labels:
    app: service3-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service3-nginx
  template:
    metadata:
      labels:
        app: service3-nginx
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.21
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux